apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
spec: 
 minReplicas: 3
 maxReplicas: 6
 targetCPUUtilizationPercentage: 22
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa
