apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: instavote
spec:
  minReplicas: 4
  MaxReplicas: 14
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instavote 
