apiVersion: v1
kind: ServiceAccount
metadata:
  name: instavote-user
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
   namespace: instavote
   name: interns
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: instavote
  name: interns
subjects:
- kind: Group
  name: interns
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: interns
  apiGroup: rbac.authorization.k8s.io
     
