apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: tier
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
        role: tier
        version: latest
    spec:
      containers:
      - image: wonchaitanya/redis:latest
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
      restartPolicy: Always
