---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: vote
spec:
    replicas: 4
    selector:
      matchLabels:
         role: vote
      matchExpressions:
        - {key: version, operator: In, values: [v1, v2, v3]}
    template:
       metadata:
         name: vote
         labels:
            role: vote
            app: python
       spec:
          containers:
            - name: vote image
              image: wonchaitanya/vote:v1
              ports: 
                - containerPort: 80
                  protocol: TCP
     
       
    
