---
apiVersion: v1
kind: Service
metadata:
    name: vote
    labels:
       role: vote
spec:
   selector:
     role: vote
   ports:
     - port: 80
       targetPort: 80
#      nodePort: 30000
   type: NodePort
   externalIPs:
     - 10.193.113.164
     - 10.193.114.43
