apiVersion: apps/v1
kind: Deployment
metadata:
   name: vote-blue
spec:
   replicas: 5
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 2
         maxUnavailable: 1
   revisionHistoryLimit: 4
   paused: false
   selector:
      matchLabels:
        role: vote
   minReadySeconds: 10
   template: 
      metadata:
        labels:
          role: vote
          app: python 
          release: bluegreen
          code: blue
      spec:
        containers:
          - name: vote-app
            image: wonchaitanya/vote:v1
            ports:
              - containerPort: 80
                protocol: TCP 
          
