apiVersion: v1
kind: Service
metadata:
  name: vote-green
  labels: 
    role: vote
spec:
  selector:
    role: vote
    release: bluegreen
    code: green 
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30001
  type: NodePort     
