apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    release: kibana
  name: kibana
  namespace: logging
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kibana
