apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: interns
  namespace: instavote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: interns
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: interns
    namespace: instavote

