apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-logging
  namespace: kube-logging
  labels:
    app: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
   name: elasticsearch-logging
   labels:
      app: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "deployments"
  - "endpoints"
  verbs:   
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-logging
  namespace: kube-logging
  labels:
    app: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  apiGroup: ""
  namespace: elasticsearch
roleRef:
  kind: ClusterRole
  name: elasticsearch-logging
  apiGroup: ""
 
  
