apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 4
  minReadySeconds: 20
  selector:
    matchLabels:
      role: vote
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v2
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote:v3
          ports:
            - containerPort: 80
              protocol: TCP
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/master 
                      operator: DoesNotExist
          preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1  
               preference:
                 matchExpressions:
                     - key: project
                       operator: In
                       values: 
                         - test
